name: metadata_fetch
description: A dart library for extracting metadata on web pages such as OpenGraph, Meta, Twitter Cards, and Structured Data (Json-LD)
version: 0.4.2
homepage: https://github.com/jg-l/metadata_fetch

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  http: ^1.2.2
  string_validator: ^1.1.0
  html: ^0.15.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
